name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build_test:
    name: "Main build and test using -> '${{ matrix.BUILD }}'"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        RUST_VER: [stable]
        BUILD: ["", "--release"]

    steps:
      - uses: actions/checkout@v4

      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          components: clippy, rustfmt
          toolchain: ${{ matrix.RUST_VER }}

      - name: Build now
        run: cargo build ${{ matrix.BUILD }}

      - name: Test it
        run: cargo test

      - name: check bin size
        run: |
          if [ "${{ matrix.BUILD }}" == "--release" ]; then
            ls -lht target/release/{client,server,client-cli,server-cli}
          elif [ "${{ matrix.BUILD }}" == "" ]; then
            ls -lht target/debug/{client,server,client-cli,server-cli}
          else
            echo any
          fi

  fmt:
    name: Check the formatting
    runs-on: ubuntu-24.04
    needs: build_test

    steps:
      - uses: actions/checkout@v4

      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          components: clippy, rustfmt
          toolchain: ${{ matrix.RUST_VER }}

      - name: Check the formatting
        run: cargo fmt --all --check

  clippy:
    name: Clippy check
    runs-on: ubuntu-24.04
    needs: build_test

    steps:
      - uses: actions/checkout@v4

      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          components: clippy, rustfmt
          toolchain: ${{ matrix.RUST_VER }}

      - name: Clippy
        run: cargo clippy
